services:
  # Logstash Consumidor
  logstash-sink:
    image: docker.elastic.co/logstash/logstash:8.11.1
    volumes:
      - ./logstash-sink/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - log-consumer-network
      - kafka-cluster-network
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m" # Limita memória
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
    depends_on:
      - elasticsearch

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Desabilita segurança (NÃO DEIXAR EM PRODUÇÃO)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - log-consumer-network
      - kafka-cluster-network
    volumes:
      - es-data:/usr/share/elasticsearch/data
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # Kibana (Interface Web)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    ports:
      - "5601:5601"
    networks:
      - log-consumer-network
      - kafka-cluster-network
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

# Rede customizada para os serviços se falarem
networks:
  log-consumer-network:
    driver: bridge
  kafka-cluster-network:
    external: true
    name: kafka-cluster-network

# Volumes para persistir dados
volumes:
  es-data:
