services:
  # Zookeeper (Dependência do Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    networks:
      - kafka-cluster-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk-data:/var/lib/zookeeper/data

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    networks:
      - kafka-cluster-network
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://${KAFKA_ADVERTISED_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: ${KAFKA_TOPIC_PARTITIONS:-1}
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m" # Limita memória
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Kafka-UI (Interface Web)
  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    networks:
      - kafka-cluster-network
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKERS: "kafka:29092"
      ZOOKEEPER_CONNECT: "zookeeper:2181"
    restart: on-failure

# Rede customizada para os serviços se falarem
networks:
  kafka-cluster-network:
    driver: bridge

# Volumes para persistir dados
volumes:
  zk-data:
  kafka-data:
