global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['jmx-exporter-kafka1:9101', 'jmx-exporter-kafka2:9102', 'jmx-exporter-kafka3:9103']
        labels:
          group: 'kafka'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
